---
include:
  - template: Auto-DevOps.gitlab-ci.yml

test_manifest:
  stage: test
  image: node:14
  cache:
    paths:
      - node_modules/
  before_script:
    - npm install --legacy-peer-deps
  script:
    - npm run validate
    - cat manifest.outlook.xml > manifest.xml
    - npm run validate

deploy_production:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  stage: deploy
  before_script:
    - pip install awscli
  script:
    - aws s3 cp ./dist s3://$S3_BUCKET_NAME_PROD/ --recursive
  environment:
    name: production
    url: https://office.mozard.nl
