---
include:
  - template: Auto-DevOps.gitlab-ci.yml

build:
  stage: build
  image: node:14
  cache:
    paths:
      - node_modules
  before_script:
    - apt-get update && apt-get install -y sudo && rm -rf /var/apt/lists/*
    - npm ci --legacy-peer-deps
  script:
    - npm run build
  artifacts:
    paths:
      - dist/

test_manifest:
  stage: test
  image: node:14
  cache:
    paths:
      - node_modules/
  before_script:
    - npm ci --legacy-peer-deps
  script:
    - npm run validate
    - cat manifest.outlook.xml > manifest.xml
    - npm run validate

deploy_production:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  stage: deploy
  script:
    - aws s3 cp ./dist s3://$S3_BUCKET_NAME_PROD/ --recursive
  environment:
    name: production
    url: https://office.mozard.nl
